# Generated by Django 3.2.25 on 2024-12-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='model',
            field=models.CharField(default='default model', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='version',
            field=models.CharField(default='default version', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
