# Generated by Django 3.2.25 on 2024-12-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20241217_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='robot_serial',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
